export default {
    facebook_icon: require("../assets/images/ic_facebook.png"),
    google_icon: require("../assets/images/ic_google.png"),
    show_eye: require("../assets/images/show.png"),
    hide_eye: require("../assets/images/hide.png"),
    Home_icon: require("../assets/images/Home.png"),
    search_icon: require("../assets/images/Search.png"),
    profile_icon: require("../assets/images/Profile.png"),
    hamsburg: require("../assets/images/drawer.png"),
    profile_pic: require("../assets/images/profile-pic.png"),
    close_icon: require("../assets/images/close-icon.png"),
    back_arrow: require("../assets/images/back-arrow.png"),
    logout_icon: require("../assets/images/logout-icon.png"),
    setting_icon: require("../assets/images/settings.png"),
    drop_down_icon: require("../assets/images/ic_down.png"),
    language_icon: require("../assets/images/language-icon.png"),
    langs_icon: require("../assets/images/langs-icon.png"),
    bgc_icon: require("../assets/images/bgc-icon.png"),
    add_icon: require("../assets/images/add-icon.png"),
    add_icon2: require("../assets/images/add2@.png"),
}