export default {
    LOGIN:"LOGIN",
    SIGNUP:"SIGNUP",
    FORGOTPASSWORD:"FORGOT PASSWORD",
    PHONE_LOGIN:"PHONE LOGIN",
    CLEAR_REDUX_STATE:'CLEAR_REDUX_STATE',
    LOGOUT:'LOGOUT',
    SIGNUP:"SIGNUP",
    GOOGLELOGIN:"GOOGLELOGIN",
    ADD_TO_CART:"ADD TO CART",
    INCREMENT:"INCREMENT",
    DECREMENT:"DECREMENT"
    
}