export default {
    LOGIN: 'Login',
    HOME: 'Home',
    SIGNUP: 'SignUp',
    PROFILE: "Profile",
    SEARCH_SCREEN: "Search ",
    TABSTACK: "Tabstack",
    DRAWER: "Drawer",
    FORGETPASSWORD: "Forget Password",
    PHONELOGIN: "Phone Login",
    OTPSCREEN: "Otp Screen",
    SLIDER: "Slider",
    CART: "Cart",
    SETTINGS: "Settings",
    PRODUCTS: "Products",
    ADMIN: "Admin",
    ACCESSORIES: " Accessories",
    CATEGORY_ITEMS: "category items",
    ITEM_DETAILS: " item details",
    OFFERS: 'offers',
    PRODUCT_SCREEN: "Product screen",
    ORDER_PRODUCT: "Order product",
    ORDER_SUMMARY: "Order Summary",
    ADDRESS_DETAILS: "Address details"

}